### ISSUE TITLE
error in loading .rmap

### ISSUE THREAD

**Issue by shiroco** [ReactionMap/RMapViewer#1]
RMapViewer cannot load .rmap. Nothing is happened after dragging a .rmap file to the Pharo (black) image window. This error was found in RMapViewer 5.1. (the current latest version) and older, which used to work before. The observation was done on macOS Sierra (version 10.12.3), Java 8 Update 111.
posted on 2017.3.24

**Comment by tomooda** [comment]
It might be the incompatibility between the VDM and Sierra because the black window means the VM is not working correctly.
I updated the VM to the latest one for Pharo 4.0 and posted it as RMapViewer-5.2-beta.zip. Please try it.

**Comment by shiroco** [comment]
The RMapViewer-5.2-beta works. Thank you very much for your quick response.
