### ISSUE TITLE
grrm2rmap

### ISSUE THREAD

**Issue by small-bamboo** [ReactionMap/RMapViewer#5]
Dear friends:
I met an error:
Usage: grrm2rmap [options] <GRRM result directory>

grrm2rmap: error: The given directory /home-yw/users/YW_qianc1/YBW/GRRM17/nbs does not contain proper GRRM log files.

**Comment by tomooda** [comment]
Do you have a file named grrm_*_DC_list.log in the directory?

**Comment by small-bamboo** [comment]
Dear Professor&nbsp;

I use &nbsp;GRRM17，but the output files are not the same as your code description&nbsp;
------------------ Original ------------------
From: Tomohiro Oda ***@***.***&gt;
Date: Mon,Jun 28,2021 5:27 PM
To: ReactionMap/RMapViewer ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ReactionMap/RMapViewer] grrm2rmap (#5)





 
Do you have a file named grrm_*_DC_list.log in the directory?

**Comment by tomooda** [comment]
I see. grrm2rmap was developed for GRRM ver. 11. The output files might have been changed since then.

**Comment by small-bamboo** [comment]
Dear friend&nbsp;
Can you develop the code? Thank you very much

------------------ Original ------------------
From: Tomohiro Oda ***@***.***&gt;
Date: Mon,Jun 28,2021 5:39 PM
To: ReactionMap/RMapViewer ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ReactionMap/RMapViewer] grrm2rmap (#5)

**Comment by small-bamboo** [comment]
Should I give you the output files?


------------------ Original ------------------
From: Tomohiro Oda ***@***.***&gt;
Date: Mon,Jun 28,2021 5:39 PM
To: ReactionMap/RMapViewer ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ReactionMap/RMapViewer] grrm2rmap (#5)





 
I see. grrm2rmap was developed for GRRM ver. 11. The output files might have been changed since then.

**Comment by shiroco** [comment]
The output file format should be the same for GRRM ver. 11, 14, and 17, at least for basic options like grrm (global reaction route map) and first only.

**Comment by small-bamboo** [comment]
What’s mean sir


------------------ Original ------------------
From: Hiroko Satoh ***@***.***&gt;
Date: Mon,Jun 28,2021 11:50 PM
To: ReactionMap/RMapViewer ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ReactionMap/RMapViewer] grrm2rmap (#5)

**Comment by shiroco** [comment]
Which calculations did you do with GRRM?

**Comment by small-bamboo** [comment]
In GRRM17, the GRRM option is replaced by ADDF，I use this way and the output file is not begin with grrm


------------------ Original ------------------
From: Hiroko Satoh ***@***.***&gt;
Date: Mon,Jun 28,2021 11:53 PM
To: ReactionMap/RMapViewer ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ReactionMap/RMapViewer] grrm2rmap (#5)

**Comment by small-bamboo** [comment]
Dear professor&nbsp;
&nbsp;I see your answer in the AFIR form, Could you please give us a video about how to use it? Thanks&nbsp;

------------------ Original ------------------
From: Hiroko Satoh ***@***.***&gt;
Date: Mon,Jun 28,2021 11:50 PM
To: ReactionMap/RMapViewer ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ReactionMap/RMapViewer] grrm2rmap (#5)





 
The output file format should be the same for GRRM ver. 11, 14, and 17, at least for basic options like grrm (global reaction route map) and first only.

**Comment by shiroco** [comment]
Yes, you are right. The GRRM option was changed to ADDF in GRRM17. The ADDF output format of GRRM17 should be the same as those from the former versions. We use GRRM11, 14, and 17. The grrm/addf outputs can be converted with grrm2rmap without any problem.

**Comment by shiroco** [comment]
If your output file name do not begin with "grrm_", please try simply change the file names (add "grrm_" to all the output files)?

**Comment by small-bamboo** [comment]
I have tried but failed. I will try it again , Thank you professor&nbsp;


------------------ Original ------------------
From: Hiroko Satoh ***@***.***&gt;
Date: Tue,Jun 29,2021 0:09 AM
To: ReactionMap/RMapViewer ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ReactionMap/RMapViewer] grrm2rmap (#5)





 
If your output file name do not begin with "grrm_", please try simply change the file names (add "grrm_" to all the output files)?

**Comment by small-bamboo** [comment]
Dear professor
Which OS should I use grrm2rmap? I use it in windows ,it gives an error .WindowsError: [Error 193] %1 不是有效的 Win32      but i did install the 32bit python

**Comment by tomooda** [comment]
I've been using it on Linux and Mac. To run grrm2rmap, you'll also need openbabel (http://openbabel.org/wiki/Main_Page).

**Comment by small-bamboo** [comment]
I have already install openbabel, but it still says [FATAL] The babel command not found.

**Comment by tomooda** [comment]
Is your installation of babel.exe accessible in the PATH environment variable?

**Comment by small-bamboo** [comment]
Dear sir
  I have this error
![QQ图片20210629200302](https://user-images.githubusercontent.com/82574986/123794183-25ffe500-d915-11eb-913d-b8882d2a7ba6.png)

**Comment by tomooda** [comment]
Do you have a file with .com extension in the output directory? please add grrm_ prefix to the .com file, too.

**Comment by small-bamboo** [comment]
Yes ,  it runs like this . Does it run successfully?
![QQ图片20210701162009](https://user-images.githubusercontent.com/82574986/124091444-6df34900-da88-11eb-82ba-fc96bdd8d6e4.png)

**Comment by tomooda** [comment]
If the tasco.rmap file is created, it ran successfully except canost.
You can use almost all functionality without canost, but if you need it, you need to compile main_canost (https://github.com/ReactionMap/main_canost).
I tested main_canost only on mac and Linux. I'm not sure if it can be compiled on windows. 
Maybe cygwin (https://www.cygwin.com/) could be a help to compile it.

**Comment by small-bamboo** [comment]
Thanks
